model_name: "google/gemma-3-4b-it"
device: "auto" # where it runs - could be gpu
torch_dtype: "auto" # numerical precision/memory - could be float32/float16/bfloat16
max_new_tokens: 512 # max answer length
temperature: 0.2 # randomness - model is now more deterministic
top_p: 0.9 # range of tokens considered during sampling
max_context_tokens: 5000 # tokens
cache_dir: "db/gemma_model" 