[project]
name = "weaviate-vector-based-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.127.0",
    "fastapi>=0.141.1",
    "flagembedding>=1.4.2",
    "llama-index>=0.14.24",
    "numpy<2",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "pyyaml>=6.0.3",
    "torch==2.2.2",
    "transformers<4.50",
    "uvicorn>=0.53.0",
    "weaviate-client[agents]>=4.23.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
